default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('DB_PORT', '5432') %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: spatial_api_dev

test:
  <<: *default
  database: spatial_api_test

production:
  <<: *default
  database: spatial_api_production
